### ISSUE TITLE
Multiple copies of js files included by browser

### ISSUE THREAD

**Issue by aiwilliams** [relevance/blue-ridge#5]
It seems that, out of the box, two copies of the js files are being loaded into the browser.

http://img.skitch.com/20090521-d7hp4seqseft9wubugf67g5wqf.jpg

**Comment by karnowski** [comment]
Adam, thanks for pointing this out.  Looks like we need to cleanup our imports.

**Comment by karnowski** [comment]
I'm seeing this on my Firebug too.

**Comment by karnowski** [comment]
This seems to be only a Firebug issue.  I've viewed the source and the "generated source" using the web developer Firefox plugin, and there is definitely only one version of each file being loaded.  Moreover, we're not seeing any of the negative behavior we've seen in the past from loading multiple copies of the files.

I think it's this old Firebug bug come back to haunt us: http://code.google.com/p/fbug/issues/detail?id=440   Basically, since we're using relative paths, Firebug gets confused.

I'm closing this issue until some negative behavior associated with multiple file loads is experienced.
